import type {
  Student,
  TrainingCourse,
  TrainingSession,
  AttendanceRecord,
  Event,
  EventParticipation,
  GradeRecord,
} from "./types"

export const mockStudents: Student[] = [
  {
    id: "s001",
    studentNumber: "KS2024001",
    name: "田中 太郎",
    furigana: "たなか たろう",
    dateOfBirth: "2006-04-15",
    gender: "男性",
    email: "tanaka.taro@example.com",
    phone: "090-1234-5678",
    postalCode: "210-0001",
    address: "神奈川県川崎市川崎区本町1-1-1",
    enrollmentDate: "2024-04-01",
    status: "在籍",
    guardianName: "田中 一郎",
    guardianPhone: "090-9876-5432",
    guardianEmail: "tanaka.ichiro@example.com",
    photoUrl: "/diverse-student-portraits.png",
  },
  {
    id: "s002",
    studentNumber: "KS2024002",
    name: "佐藤 花子",
    furigana: "さとう はなこ",
    dateOfBirth: "2006-08-22",
    gender: "女性",
    email: "sato.hanako@example.com",
    phone: "080-2345-6789",
    postalCode: "210-0002",
    address: "神奈川県川崎市川崎区砂子2-2-2",
    enrollmentDate: "2024-04-01",
    status: "在籍",
    guardianName: "佐藤 美咲",
    guardianPhone: "080-8765-4321",
    guardianEmail: "sato.misaki@example.com",
    photoUrl: "/female-student-portrait.png",
  },
  {
    id: "s003",
    studentNumber: "KS2024003",
    name: "鈴木 次郎",
    furigana: "すずき じろう",
    dateOfBirth: "2005-12-10",
    gender: "男性",
    email: "suzuki.jiro@example.com",
    phone: "070-3456-7890",
    postalCode: "210-0003",
    address: "神奈川県川崎市川崎区堀之内3-3-3",
    enrollmentDate: "2024-04-01",
    status: "在籍",
    guardianName: "鈴木 和子",
    guardianPhone: "070-7654-3210",
    guardianEmail: "suzuki.kazuko@example.com",
    photoUrl: "/male-student-portrait.png",
  },
]

export const mockTrainingCourses: TrainingCourse[] = [
  {
    id: "tc001",
    code: "AQ101",
    name: "淡水魚飼育基礎",
    description: "淡水魚の基本的な飼育方法と水質管理を学ぶ",
    category: "飼育実習",
    targetGrade: 1,
    maxCapacity: 15,
    duration: 2,
    isActive: true,
  },
  {
    id: "tc002",
    code: "AQ102",
    name: "海水魚飼育実習",
    description: "海水魚の飼育と海水水槽の管理技術を習得",
    category: "飼育実習",
    targetGrade: 1,
    maxCapacity: 12,
    duration: 2,
    isActive: true,
  },
  {
    id: "tc003",
    code: "WQ201",
    name: "水質検査実習",
    description: "水質検査の各種測定方法と分析技術",
    category: "水質管理",
    targetGrade: 1,
    maxCapacity: 20,
    duration: 1.5,
    isActive: true,
  },
  {
    id: "tc004",
    code: "AN301",
    name: "動物看護基礎",
    description: "水生動物の健康管理と病気の予防",
    category: "動物看護",
    targetGrade: 2,
    maxCapacity: 15,
    duration: 2,
    isActive: true,
  },
]

export const mockTrainingSessions: TrainingSession[] = [
  {
    id: "ts001",
    courseId: "tc001",
    sessionNumber: 1,
    date: "2025-01-10",
    startTime: "09:00",
    endTime: "11:00",
    instructor: "山田 健太",
    location: "淡水飼育室A",
    description: "オリエンテーションと基本的な給餌方法",
    status: "完了",
    maxParticipants: 15,
  },
  {
    id: "ts002",
    courseId: "tc001",
    sessionNumber: 2,
    date: "2025-01-17",
    startTime: "09:00",
    endTime: "11:00",
    instructor: "山田 健太",
    location: "淡水飼育室A",
    description: "水質測定と水換え作業",
    status: "完了",
    maxParticipants: 15,
  },
  {
    id: "ts003",
    courseId: "tc002",
    sessionNumber: 1,
    date: "2025-01-15",
    startTime: "13:00",
    endTime: "15:00",
    instructor: "中村 美咲",
    location: "海水飼育室B",
    description: "海水魚の種類と特性について",
    status: "完了",
    maxParticipants: 12,
  },
  {
    id: "ts004",
    courseId: "tc003",
    sessionNumber: 1,
    date: "2025-01-20",
    startTime: "10:00",
    endTime: "11:30",
    instructor: "高橋 誠",
    location: "水質検査室",
    description: "pH、アンモニア測定実習",
    status: "予定",
    maxParticipants: 20,
  },
]

export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: "ar001",
    sessionId: "ts001",
    studentId: "s001",
    status: "出席",
    checkInTime: "08:55",
    checkOutTime: "11:05",
    proficiencyLevel: 4,
    feedback: "積極的に取り組んでいた。給餌のタイミングが適切",
    notes: "",
  },
  {
    id: "ar002",
    sessionId: "ts001",
    studentId: "s002",
    status: "出席",
    checkInTime: "09:00",
    checkOutTime: "11:00",
    proficiencyLevel: 5,
    feedback: "非常に丁寧な作業。理解度も高い",
    notes: "",
  },
  {
    id: "ar003",
    sessionId: "ts001",
    studentId: "s003",
    status: "遅刻",
    checkInTime: "09:20",
    checkOutTime: "11:00",
    proficiencyLevel: 3,
    feedback: "遅刻したが、その後は真面目に参加",
    notes: "電車遅延",
  },
  {
    id: "ar004",
    sessionId: "ts002",
    studentId: "s001",
    status: "出席",
    checkInTime: "08:58",
    checkOutTime: "11:02",
    proficiencyLevel: 4,
    feedback: "水質測定の手順を正確に実施できた",
    notes: "",
  },
  {
    id: "ar005",
    sessionId: "ts002",
    studentId: "s002",
    status: "出席",
    checkInTime: "09:00",
    checkOutTime: "11:00",
    proficiencyLevel: 5,
    feedback: "優れた理解力と実践力",
    notes: "",
  },
  {
    id: "ar006",
    sessionId: "ts002",
    studentId: "s003",
    status: "欠席",
    proficiencyLevel: undefined,
    feedback: "",
    notes: "体調不良で欠席",
  },
]

export const mockEvents: Event[] = [
  {
    id: "e001",
    name: "沖縄美ら海水族館 修学旅行",
    type: "修学旅行",
    date: "2025-03-15",
    endDate: "2025-03-17",
    location: "沖縄県",
    description: "美ら海水族館でのバックヤードツアーと飼育員との交流",
    fee: 85000,
    requiresConsent: true,
    requiresPayment: true,
    capacity: 60,
    status: "募集中",
  },
  {
    id: "e002",
    name: "アクアリウム業界セミナー",
    type: "特別講義",
    date: "2025-02-10",
    location: "カワスイ ホール",
    description: "業界のプロフェッショナルによる特別講演",
    fee: 0,
    requiresConsent: false,
    requiresPayment: false,
    capacity: 80,
    status: "募集中",
  },
]

export const mockEventParticipations: EventParticipation[] = [
  {
    id: "ep001",
    eventId: "e001",
    studentId: "s001",
    applicationDate: "2025-01-05",
    status: "申込",
    consentReceived: true,
    paymentStatus: "支払済み",
    notes: "",
  },
  {
    id: "ep002",
    eventId: "e001",
    studentId: "s002",
    applicationDate: "2025-01-08",
    status: "申込",
    consentReceived: true,
    paymentStatus: "未払い",
    notes: "",
  },
  {
    id: "ep003",
    eventId: "e002",
    studentId: "s001",
    applicationDate: "2025-01-10",
    status: "申込",
    consentReceived: false,
    paymentStatus: "免除",
    notes: "",
  },
]

export const mockGradeRecords: GradeRecord[] = [
  {
    id: "gr001",
    studentId: "s001",
    courseId: "tc001",
    semester: "2024年度 前期",
    midtermScore: 85,
    finalScore: 88,
    overallGrade: "A",
    attendance: 95,
    comments: "優れた理解力と実践力を示している",
  },
  {
    id: "gr002",
    studentId: "s002",
    courseId: "tc001",
    semester: "2024年度 前期",
    midtermScore: 92,
    finalScore: 95,
    overallGrade: "A",
    attendance: 100,
    comments: "非常に優秀。模範的な学習態度",
  },
  {
    id: "gr003",
    studentId: "s003",
    courseId: "tc001",
    semester: "2024年度 前期",
    midtermScore: 75,
    finalScore: 78,
    overallGrade: "B",
    attendance: 85,
    comments: "基礎は理解している。出席率の向上が必要",
  },
]
